app_name = "hotel_pms"
app_title = "Hotel PMS"
app_publisher = "The Batu Hotel & Villas"
app_description = "Native hotel property management system integrated with ERPNext"
app_email = "admin@example.com"
app_license = "GPL-3.0"

required_apps = ["erpnext"]

app_include_js = ["/assets/hotel_pms/js/photo_policy.js", "/assets/hotel_pms/js/property_scope.js"]

doctype_js = {
    "Payment Entry": "public/js/payment_entry.js",
}

override_whitelisted_methods = {
    "frappe.handler.upload_file": "hotel_pms.media.upload_file",
    "upload_file": "hotel_pms.media.upload_file",
}

add_to_apps_screen = [
    {
        "name": "hotel_pms",
        "logo": "/assets/hotel_pms/images/logo.svg",
        "title": "Hotel PMS",
        "route": "/app/hotel-front-desk",
        "has_permission": "hotel_pms.api.has_app_permission",
    }
]

doc_events = {
    "Hotel Reservation": {"after_insert": "hotel_pms.webhooks.emit_document_event", "on_update": "hotel_pms.webhooks.emit_document_event", "on_submit": "hotel_pms.webhooks.emit_document_event", "on_cancel": "hotel_pms.webhooks.emit_document_event"},
    "Hotel Housekeeping Task": {"after_insert": "hotel_pms.webhooks.emit_document_event", "on_update": "hotel_pms.webhooks.emit_document_event"},
    "Hotel Maintenance Ticket": {"after_insert": "hotel_pms.webhooks.emit_document_event", "on_update": "hotel_pms.webhooks.emit_document_event"},
    "Hotel Restaurant Order": {"after_insert": "hotel_pms.webhooks.emit_document_event", "on_update": "hotel_pms.webhooks.emit_document_event"},
    "Hotel Laundry Order": {"after_insert": "hotel_pms.webhooks.emit_document_event", "on_update": "hotel_pms.webhooks.emit_document_event"},
    "Hotel Experience Booking": {"after_insert": "hotel_pms.webhooks.emit_document_event", "on_update": "hotel_pms.webhooks.emit_document_event"},
    "File": {
        "before_insert": "hotel_pms.media.validate_file_upload",
    },
    "Payment Entry": {
        "on_submit": "hotel_pms.integrations.payment_entry.on_submit",
        "on_cancel": "hotel_pms.integrations.payment_entry.on_cancel",
    },
    "Sales Invoice": {
        "on_submit": "hotel_pms.integrations.sales_invoice.on_submit",
        "on_cancel": "hotel_pms.integrations.sales_invoice.on_cancel",
        "on_trash": "hotel_pms.integrations.sales_invoice.on_trash",
    },
    "POS Invoice": {
        "on_submit": "hotel_pms.integrations.pos_invoice.on_submit",
        "on_cancel": "hotel_pms.integrations.pos_invoice.on_cancel",
    },
    "Stock Entry": {
        "on_submit": "hotel_pms.fnb_inventory.on_stock_entry_submit",
        "on_cancel": "hotel_pms.fnb_inventory.on_stock_entry_cancel",
    }
}

scheduler_events = {
    "cron": {
        "*/5 * * * *": ["hotel_pms.platform.worker_heartbeat", "hotel_pms.webhooks.process_webhook_queue", "hotel_pms.communications.process_message_queue"],
        "*/15 * * * *": ["hotel_pms.front_desk.process_no_show_candidates", "hotel_pms.operations.monitor_operation_slas", "hotel_pms.services.monitor_guest_services"],
        "17 * * * *": ["hotel_pms.platform.capture_health_snapshot"],
        "30 4 * * *": ["hotel_pms.intelligence.run_scheduled_intelligence"],
    },
    "daily": [
        "hotel_pms.tasks.create_housekeeping_tasks",
        "hotel_pms.tasks.create_preventive_maintenance_tasks",
        "hotel_pms.tasks.expire_tentative_group_holds",
        "hotel_pms.tasks.release_group_room_blocks_at_cutoff",
        "hotel_pms.reconcile.reconcile_erpnext_links",
        "hotel_pms.revenue.expire_rate_approvals",
        "hotel_pms.revenue.update_travel_agent_settlement_statuses",
        "hotel_pms.guest_portal.expire_guest_tokens",
        "hotel_pms.guest_portal.expire_blacklist_records",
        "hotel_pms.platform.cleanup_platform_records",
        "hotel_pms.platform.review_privacy_retention",
        "hotel_pms.media.purge_verify_discard_documents",
    ]
}

before_install = "hotel_pms.install.before_install"
after_install = "hotel_pms.install.after_install"


extend_bootinfo = "hotel_pms.platform.extend_bootinfo"

permission_query_conditions = {
    'Hotel Folio Transfer': "hotel_pms.permissions.hotel_folio_transfer_query",
    'Hotel Cancellation Policy': "hotel_pms.permissions.hotel_cancellation_policy_query",
    'Hotel Cancellation': "hotel_pms.permissions.hotel_cancellation_query",
    'Hotel Voucher Redemption': "hotel_pms.permissions.hotel_voucher_redemption_query",
    'Hotel Guest Privacy Request': "hotel_pms.permissions.hotel_guest_privacy_request_query",
    'Hotel Guest Consent': "hotel_pms.permissions.hotel_guest_consent_query",
    'Hotel Guest Action Log': "hotel_pms.permissions.hotel_guest_action_log_query",
    'Hotel Guest Access Token': "hotel_pms.permissions.hotel_guest_access_token_query",
    'Hotel User Property Access': "hotel_pms.permissions.hotel_user_property_access_query",
    'Hotel ERP Sync Log': "hotel_pms.permissions.hotel_erp_sync_log_query",
    'Hotel Property': "hotel_pms.permissions.hotel_property_query",
    'Hotel Reservation': "hotel_pms.permissions.hotel_reservation_query",
    'Hotel Room': "hotel_pms.permissions.hotel_room_query",
    'Hotel Room Type': "hotel_pms.permissions.hotel_room_type_query",
    'Hotel Folio': "hotel_pms.permissions.hotel_folio_query",
    'Hotel Group Booking': "hotel_pms.permissions.hotel_group_booking_query",
    'Hotel Group Folio': "hotel_pms.permissions.hotel_group_folio_query",
    'Hotel Banquet Event Order': "hotel_pms.permissions.hotel_banquet_event_order_query",
    'Hotel Function Space': "hotel_pms.permissions.hotel_function_space_query",
    'Hotel Package Template': "hotel_pms.permissions.hotel_package_template_query",
    'Hotel Package Posting': "hotel_pms.permissions.hotel_package_posting_query",
    'Hotel Rate Plan': "hotel_pms.permissions.hotel_rate_plan_query",
    'Hotel Rate Season': "hotel_pms.permissions.hotel_rate_season_query",
    'Hotel Rate Calendar': "hotel_pms.permissions.hotel_rate_calendar_query",
    'Hotel Rate Approval': "hotel_pms.permissions.hotel_rate_approval_query",
    'Hotel Voucher': "hotel_pms.permissions.hotel_voucher_query",
    'Hotel Travel Agent Contract': "hotel_pms.permissions.hotel_travel_agent_contract_query",
    'Hotel Travel Agent Settlement': "hotel_pms.permissions.hotel_travel_agent_settlement_query",
    'Hotel Tax Profile': "hotel_pms.permissions.hotel_tax_profile_query",
    'Hotel City Ledger Account': "hotel_pms.permissions.hotel_city_ledger_account_query",
    'Hotel City Ledger Folio': "hotel_pms.permissions.hotel_city_ledger_folio_query",
    'Hotel Direct Bill Approval': "hotel_pms.permissions.hotel_direct_bill_approval_query",
    'Hotel Cashier Shift': "hotel_pms.permissions.hotel_cashier_shift_query",
    'Hotel Cashier Movement': "hotel_pms.permissions.hotel_cashier_movement_query",
    'Hotel Housekeeping Task': "hotel_pms.permissions.hotel_housekeeping_task_query",
    'Hotel Room Inspection': "hotel_pms.permissions.hotel_room_inspection_query",
    'Hotel Lost and Found': "hotel_pms.permissions.hotel_lost_and_found_query",
    'Hotel Maintenance Ticket': "hotel_pms.permissions.hotel_maintenance_ticket_query",
    'Hotel Preventive Maintenance Schedule': "hotel_pms.permissions.hotel_preventive_maintenance_schedule_query",
    'Hotel Room Status Log': "hotel_pms.permissions.hotel_room_status_log_query",
    'Hotel SOP Candidate': "hotel_pms.permissions.hotel_sop_candidate_query",
    'Hotel Cleaning Checklist Template': "hotel_pms.permissions.hotel_cleaning_checklist_template_query",
    'Hotel Stay Change Log': "hotel_pms.permissions.hotel_stay_change_log_query",
    'Hotel Guest Registration': "hotel_pms.permissions.hotel_guest_registration_query",
    'Hotel Outlet': "hotel_pms.permissions.hotel_outlet_query",
    'Hotel Dining Area': "hotel_pms.permissions.hotel_dining_area_query",
    'Hotel Restaurant Table': "hotel_pms.permissions.hotel_restaurant_table_query",
    'Hotel Table Reservation': "hotel_pms.permissions.hotel_table_reservation_query",
    'Hotel Outlet Menu Item': "hotel_pms.permissions.hotel_outlet_menu_item_query",
    'Hotel Restaurant Order': "hotel_pms.permissions.hotel_restaurant_order_query",
    'Hotel Restaurant Bill Split': "hotel_pms.permissions.hotel_restaurant_bill_split_query",
    'Hotel Kitchen Ticket': "hotel_pms.permissions.hotel_kitchen_ticket_query",
    'Hotel Laundry Rate': "hotel_pms.permissions.hotel_laundry_rate_query",
    'Hotel Laundry Order': "hotel_pms.permissions.hotel_laundry_order_query",
    'Hotel Guest Experience': "hotel_pms.permissions.hotel_guest_experience_query",
    'Hotel Experience Booking': "hotel_pms.permissions.hotel_experience_booking_query",
    'Hotel Shift Handover': "hotel_pms.permissions.hotel_shift_handover_query",
    'Hotel Guest Property Note': "hotel_pms.permissions.hotel_guest_property_note_query",
    'Hotel Migration Batch': "hotel_pms.permissions.hotel_migration_batch_query",
    'Hotel Migration Row': "hotel_pms.permissions.hotel_migration_row_query",
    'Hotel Webhook Subscription': "hotel_pms.permissions.hotel_webhook_subscription_query",
    'Hotel Webhook Delivery': "hotel_pms.permissions.hotel_webhook_delivery_query",
    'Hotel API Idempotency': "hotel_pms.permissions.hotel_api_idempotency_query",
    'Hotel Production Gate Run': "hotel_pms.permissions.hotel_production_gate_run_query",
    'Hotel Channel Connection': "hotel_pms.permissions.hotel_channel_connection_query",
    'Hotel Guest Message': "hotel_pms.permissions.hotel_guest_message_query",
    'Hotel Menu Import Batch': "hotel_pms.permissions.hotel_menu_import_batch_query",
    'Hotel Rehearsal Run': "hotel_pms.permissions.hotel_rehearsal_run_query",
    'Hotel Parallel Run Batch': "hotel_pms.permissions.hotel_parallel_run_batch_query",
    'Hotel Validation Evidence': "hotel_pms.permissions.hotel_validation_evidence_query",
    'Hotel Intelligence Config': "hotel_pms.permissions.hotel_intelligence_config_query",
    'Hotel Intelligence Run': "hotel_pms.permissions.hotel_intelligence_run_query",
    'Hotel Intelligence Decision': "hotel_pms.permissions.hotel_intelligence_decision_query",
    'Hotel Night Audit Finding': "hotel_pms.permissions.hotel_night_audit_finding_query",
    'Hotel Payment Correction': "hotel_pms.permissions.hotel_payment_correction_query",
    'Hotel Integration Connection': "hotel_pms.permissions.hotel_integration_connection_query",
}

has_permission = {
    'Hotel Folio Transfer': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Cancellation Policy': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Cancellation': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Voucher Redemption': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Guest Privacy Request': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Guest Consent': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Guest Action Log': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Guest Access Token': "hotel_pms.permissions.property_document_has_permission",
    'Hotel User Property Access': "hotel_pms.permissions.property_document_has_permission",
    'Hotel ERP Sync Log': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Property': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Reservation': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Room': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Room Type': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Folio': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Group Booking': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Group Folio': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Banquet Event Order': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Function Space': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Package Template': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Package Posting': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Rate Plan': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Rate Season': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Rate Calendar': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Rate Approval': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Voucher': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Travel Agent Contract': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Travel Agent Settlement': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Tax Profile': "hotel_pms.permissions.property_document_has_permission",
    'Hotel City Ledger Account': "hotel_pms.permissions.property_document_has_permission",
    'Hotel City Ledger Folio': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Direct Bill Approval': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Cashier Shift': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Cashier Movement': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Housekeeping Task': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Room Inspection': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Lost and Found': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Maintenance Ticket': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Preventive Maintenance Schedule': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Room Status Log': "hotel_pms.permissions.property_document_has_permission",
    'Hotel SOP Candidate': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Cleaning Checklist Template': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Stay Change Log': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Guest Registration': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Outlet': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Dining Area': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Restaurant Table': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Table Reservation': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Outlet Menu Item': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Restaurant Order': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Restaurant Bill Split': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Kitchen Ticket': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Laundry Rate': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Laundry Order': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Guest Experience': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Experience Booking': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Shift Handover': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Guest Property Note': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Migration Batch': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Migration Row': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Webhook Subscription': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Webhook Delivery': "hotel_pms.permissions.property_document_has_permission",
    'Hotel API Idempotency': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Production Gate Run': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Channel Connection': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Guest Message': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Menu Import Batch': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Rehearsal Run': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Parallel Run Batch': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Validation Evidence': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Intelligence Config': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Intelligence Run': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Intelligence Decision': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Night Audit Finding': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Payment Correction': "hotel_pms.permissions.property_document_has_permission",
    'Hotel Integration Connection': "hotel_pms.permissions.property_document_has_permission",
}
