from hotel_pms.platform import permission_query, document_has_permission

def property_document_has_permission(doc,user=None,permission_type=None):
    return document_has_permission(doc,user,permission_type)
def hotel_property_query(user=None): return permission_query('Hotel Property',user)
def hotel_reservation_query(user=None): return permission_query('Hotel Reservation',user)
def hotel_room_query(user=None): return permission_query('Hotel Room',user)
def hotel_room_type_query(user=None): return permission_query('Hotel Room Type',user)
def hotel_folio_query(user=None): return permission_query('Hotel Folio',user)
def hotel_group_booking_query(user=None): return permission_query('Hotel Group Booking',user)
def hotel_group_folio_query(user=None): return permission_query('Hotel Group Folio',user)
def hotel_banquet_event_order_query(user=None): return permission_query('Hotel Banquet Event Order',user)
def hotel_function_space_query(user=None): return permission_query('Hotel Function Space',user)
def hotel_package_template_query(user=None): return permission_query('Hotel Package Template',user)
def hotel_package_posting_query(user=None): return permission_query('Hotel Package Posting',user)
def hotel_rate_plan_query(user=None): return permission_query('Hotel Rate Plan',user)
def hotel_rate_season_query(user=None): return permission_query('Hotel Rate Season',user)
def hotel_rate_calendar_query(user=None): return permission_query('Hotel Rate Calendar',user)
def hotel_rate_approval_query(user=None): return permission_query('Hotel Rate Approval',user)
def hotel_voucher_query(user=None): return permission_query('Hotel Voucher',user)
def hotel_travel_agent_contract_query(user=None): return permission_query('Hotel Travel Agent Contract',user)
def hotel_travel_agent_settlement_query(user=None): return permission_query('Hotel Travel Agent Settlement',user)
def hotel_tax_profile_query(user=None): return permission_query('Hotel Tax Profile',user)
def hotel_city_ledger_account_query(user=None): return permission_query('Hotel City Ledger Account',user)
def hotel_city_ledger_folio_query(user=None): return permission_query('Hotel City Ledger Folio',user)
def hotel_direct_bill_approval_query(user=None): return permission_query('Hotel Direct Bill Approval',user)
def hotel_cashier_shift_query(user=None): return permission_query('Hotel Cashier Shift',user)
def hotel_cashier_movement_query(user=None): return permission_query('Hotel Cashier Movement',user)
def hotel_housekeeping_task_query(user=None): return permission_query('Hotel Housekeeping Task',user)
def hotel_room_inspection_query(user=None): return permission_query('Hotel Room Inspection',user)
def hotel_lost_and_found_query(user=None): return permission_query('Hotel Lost and Found',user)
def hotel_maintenance_ticket_query(user=None): return permission_query('Hotel Maintenance Ticket',user)
def hotel_preventive_maintenance_schedule_query(user=None): return permission_query('Hotel Preventive Maintenance Schedule',user)
def hotel_room_status_log_query(user=None): return permission_query('Hotel Room Status Log',user)
def hotel_sop_candidate_query(user=None): return permission_query('Hotel SOP Candidate',user)
def hotel_cleaning_checklist_template_query(user=None): return permission_query('Hotel Cleaning Checklist Template',user)
def hotel_stay_change_log_query(user=None): return permission_query('Hotel Stay Change Log',user)
def hotel_guest_registration_query(user=None): return permission_query('Hotel Guest Registration',user)
def hotel_outlet_query(user=None): return permission_query('Hotel Outlet',user)
def hotel_dining_area_query(user=None): return permission_query('Hotel Dining Area',user)
def hotel_restaurant_table_query(user=None): return permission_query('Hotel Restaurant Table',user)
def hotel_table_reservation_query(user=None): return permission_query('Hotel Table Reservation',user)
def hotel_outlet_menu_item_query(user=None): return permission_query('Hotel Outlet Menu Item',user)
def hotel_restaurant_order_query(user=None): return permission_query('Hotel Restaurant Order',user)
def hotel_restaurant_bill_split_query(user=None): return permission_query('Hotel Restaurant Bill Split',user)
def hotel_kitchen_ticket_query(user=None): return permission_query('Hotel Kitchen Ticket',user)
def hotel_laundry_rate_query(user=None): return permission_query('Hotel Laundry Rate',user)
def hotel_laundry_order_query(user=None): return permission_query('Hotel Laundry Order',user)
def hotel_guest_experience_query(user=None): return permission_query('Hotel Guest Experience',user)
def hotel_experience_booking_query(user=None): return permission_query('Hotel Experience Booking',user)
def hotel_shift_handover_query(user=None): return permission_query('Hotel Shift Handover',user)
def hotel_guest_property_note_query(user=None): return permission_query('Hotel Guest Property Note',user)
def hotel_migration_batch_query(user=None): return permission_query('Hotel Migration Batch',user)
def hotel_migration_row_query(user=None): return permission_query('Hotel Migration Row',user)
def hotel_webhook_subscription_query(user=None): return permission_query('Hotel Webhook Subscription',user)
def hotel_webhook_delivery_query(user=None): return permission_query('Hotel Webhook Delivery',user)
def hotel_api_idempotency_query(user=None): return permission_query('Hotel API Idempotency',user)
def hotel_user_property_access_query(user=None): return permission_query('Hotel User Property Access',user)
def hotel_erp_sync_log_query(user=None): return permission_query('Hotel ERP Sync Log',user)
def hotel_guest_access_token_query(user=None): return permission_query('Hotel Guest Access Token',user)
def hotel_guest_action_log_query(user=None): return permission_query('Hotel Guest Action Log',user)
def hotel_guest_consent_query(user=None): return permission_query('Hotel Guest Consent',user)
def hotel_guest_privacy_request_query(user=None): return permission_query('Hotel Guest Privacy Request',user)
def hotel_voucher_redemption_query(user=None): return permission_query('Hotel Voucher Redemption',user)
def hotel_cancellation_query(user=None): return permission_query('Hotel Cancellation',user)
def hotel_cancellation_policy_query(user=None): return permission_query('Hotel Cancellation Policy',user)
def hotel_folio_transfer_query(user=None): return permission_query('Hotel Folio Transfer',user)


def hotel_production_gate_run_query(user=None):
    return permission_query("Hotel Production Gate Run", user)

def hotel_channel_connection_query(user=None): return permission_query("Hotel Channel Connection",user)
def hotel_guest_message_query(user=None): return permission_query("Hotel Guest Message",user)
