frappe.pages["hotel-distribution-console"].on_page_load=function(wrapper){
 const page=frappe.ui.make_app_page({parent:wrapper,title:__("Hotel Distribution Console"),single_column:true});
 const property=page.add_field({label:__("Property"),fieldtype:"Link",fieldname:"property",options:"Hotel Property",reqd:1,change:load});
 page.set_primary_action(__("New Connection"),()=>frappe.new_doc("Hotel Distribution Connection",{property:property.get_value()}),"add");
 page.add_inner_button(__("Refresh"),load);
 const body=$(`<div><style>.hdc-cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px;margin-top:12px}.hdc-card{border:1px solid var(--border-color);border-radius:8px;padding:14px}.hdc-card.failed{border-color:var(--red-300)}.hdc-actions button{margin:4px 4px 0 0}.hdc-table{width:100%;margin-top:14px}.hdc-table th,.hdc-table td{padding:7px;border-bottom:1px solid var(--border-color);vertical-align:top}</style><div class="hdc-cards"></div><div class="hdc-review"></div></div>`).appendTo(page.main);
 const e=x=>frappe.utils.escape_html(String(x??""));
 body.on('click','[data-test]',async function(){await frappe.call({method:'hotel_pms.distribution.test_connection',args:{connection:$(this).data('test')},freeze:true});load();});
 body.on('click','[data-sync]',async function(){await frappe.call({method:'hotel_pms.distribution.sync_ical_connection',args:{connection:$(this).data('sync')},freeze:true});load();});
 body.on('click','[data-token]',async function(){const r=await frappe.call({method:'hotel_pms.distribution.rotate_feed_token',args:{connection:$(this).data('token')}});const d=r.message;frappe.msgprint({title:__('New iCal Feed URL'),message:`<p>${__('Copy this URL now. The raw token is not stored.')}</p><textarea class="form-control" rows="4">${e(d.url)}</textarea>`,wide:true});});
 body.on('click','[data-doc]',function(){frappe.set_route('Form',$(this).data('doctype'),$(this).data('doc'));});
 async function load(){const p=property.get_value();if(!p)return;const r=await frappe.call({method:'hotel_pms.distribution.get_distribution_dashboard',args:{property:p}});const d=r.message||{};
  body.find('.hdc-cards').html((d.connections||[]).map(c=>`<div class="hdc-card ${c.status==='Failed'?'failed':''}"><h4>${e(c.provider)} <small>${e(c.maturity_status)}</small></h4><p>${e(c.status)} · ${c.enabled?__('Enabled'):__('Disabled')}</p><small>${e(c.last_test_status||'Not tested')}<br>${e(c.last_sync_status||'Not synced')}<br>${e(c.last_push_status||'Not pushed')}</small><div class="hdc-actions"><button class="btn btn-xs btn-default" data-doc="${e(c.name)}" data-doctype="Hotel Distribution Connection">${__('Open')}</button><button class="btn btn-xs btn-default" data-test="${e(c.name)}">${__('Test')}</button>${c.provider==='Generic iCal'?`<button class="btn btn-xs btn-default" data-sync="${e(c.name)}">${__('Sync')}</button><button class="btn btn-xs btn-default" data-token="${e(c.name)}">${__('Rotate Feed Token')}</button>`:''}</div></div>`).join('')||`<div class="text-muted">${__('No distribution connections')}</div>`);
  const review=(d.review_events||[]).map(x=>`<tr data-doc="${e(x.name)}" data-doctype="Hotel Distribution Event"><td>${e(x.status)}</td><td>${e(x.event_type)}</td><td>${e(x.external_reference)}</td><td>${e(x.arrival_date)} → ${e(x.departure_date)}</td><td>${e(x.error||x.summary)}</td></tr>`).join('');
  const conflicts=(d.conflicts||[]).map(x=>`<tr><td>${e(x.classification)}</td><td>${e(x.room||x.room_type)}</td><td>${e(x.arrival_date)} → ${e(x.departure_date)}</td><td>${e(x.a)} / ${e(x.b)}</td></tr>`).join('');
  body.find('.hdc-review').html(`<h4>${__('Needs Review')}</h4><table class="hdc-table"><thead><tr><th>${__('Status')}</th><th>${__('Type')}</th><th>${__('External Ref')}</th><th>${__('Dates')}</th><th>${__('Detail')}</th></tr></thead><tbody>${review||`<tr><td colspan="5">${__('No review items')}</td></tr>`}</tbody></table><h4>${__('iCal Conflict Detection')}</h4><table class="hdc-table"><thead><tr><th>${__('Classification')}</th><th>${__('Room')}</th><th>${__('Overlap')}</th><th>${__('Events')}</th></tr></thead><tbody>${conflicts||`<tr><td colspan="4">${__('No overlaps')}</td></tr>`}</tbody></table>`);
 }
 frappe.db.get_single_value('Hotel PMS Settings','default_property').then(v=>{if(v)property.set_value(v)});
};