frappe.pages["hotel-intelligence-console"].on_page_load=function(wrapper){
 const page=frappe.ui.make_app_page({parent:wrapper,title:__("Hotel Intelligence Console"),single_column:true});
 const property=page.add_field({label:__("Property"),fieldtype:"Link",fieldname:"property",options:"Hotel Property",reqd:1});
 const date=page.add_field({label:__("Business Date"),fieldtype:"Date",fieldname:"business_date",default:frappe.datetime.get_today()});
 page.add_inner_button(__("Refresh"),load);
 page.add_inner_button(__("Run Night Audit Scan"),async()=>{if(!property.get_value()){frappe.msgprint(__("Select a property."));return;}await frappe.call({method:"hotel_pms.intelligence.run_night_audit_scan",args:{property:property.get_value(),business_date:date.get_value()},freeze:true,freeze_message:__("Scanning governed operational and ERPNext evidence...")});load();});
 page.add_inner_button(__("Seed Integration Registry"),async()=>{await frappe.call({method:"hotel_pms.intelligence.seed_integration_registry",freeze:true});load();});
 const body=$(`<div><style>.hic-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px}.hic-card{padding:14px;border:1px solid var(--border-color);border-radius:8px}.hic-card b{display:block;font-size:22px}.hic-table{width:100%;margin-top:16px}.hic-table th,.hic-table td{padding:7px;border-bottom:1px solid var(--border-color);vertical-align:top}.sev-Critical{color:var(--red-600);font-weight:700}.sev-Warning{color:var(--orange-600);font-weight:700}</style><div class="hic-grid"></div><div class="hic-content"></div></div>`).appendTo(page.main);
 const e=x=>frappe.utils.escape_html(String(x??""));
 async function load(){if(!property.get_value()){body.find('.hic-content').html(`<div class="text-muted">${__("Select a property to load intelligence evidence.")}</div>`);return;}const r=await frappe.call({method:"hotel_pms.intelligence.get_intelligence_dashboard",args:{property:property.get_value(),business_date:date.get_value()}});const d=r.message||{};body.find('.hic-grid').html(Object.entries(d.cards||{}).map(([k,v])=>`<div class="hic-card"><span>${e(k)}</span><b>${e(v)}</b></div>`).join(''));const findings=(d.findings||[]).map(x=>`<tr><td class="sev-${e(x.severity)}">${e(x.severity)}</td><td>${e(x.finding_type)}</td><td>${e(x.reference_name)}</td><td>${e(x.description)}</td><td>${e(x.status)}</td></tr>`).join('');const decisions=(d.decisions||[]).map(x=>`<tr><td>${e(x.agent_type)}</td><td>${e(x.decision_type)}</td><td>${e(x.confidence)}</td><td>${e(x.status)}</td></tr>`).join('');const integrations=(d.integrations||[]).map(x=>`<tr><td>${e(x.provider_name)}</td><td>${e(x.category)}</td><td>${e(x.maturity_status)}</td><td>${e(x.connection_status||'Not Configured')}</td></tr>`).join('');body.find('.hic-content').html(`<h4>${__("Night Audit Findings")}</h4><table class="hic-table"><thead><tr><th>${__("Severity")}</th><th>${__("Type")}</th><th>${__("Reference")}</th><th>${__("Description")}</th><th>${__("Status")}</th></tr></thead><tbody>${findings||`<tr><td colspan="5">${__("No findings")}</td></tr>`}</tbody></table><h4>${__("Recent Decisions")}</h4><table class="hic-table"><thead><tr><th>${__("Agent")}</th><th>${__("Decision")}</th><th>${__("Confidence")}</th><th>${__("Status")}</th></tr></thead><tbody>${decisions||`<tr><td colspan="4">${__("No decisions")}</td></tr>`}</tbody></table><h4>${__("Integration Registry")}</h4><table class="hic-table"><thead><tr><th>${__("Provider")}</th><th>${__("Category")}</th><th>${__("Maturity")}</th><th>${__("Connection")}</th></tr></thead><tbody>${integrations||`<tr><td colspan="4">${__("Registry not seeded")}</td></tr>`}</tbody></table>`)}
};