frappe.pages["hotel-turnover-planner"].on_page_load=function(wrapper){
 const page=frappe.ui.make_app_page({parent:wrapper,title:__("Hotel Turnover Planner"),single_column:true});
 const property=page.add_field({label:__("Property"),fieldtype:"Link",fieldname:"property",options:"Hotel Property",reqd:1,change:load});
 const start=page.add_field({label:__("Start"),fieldtype:"Date",fieldname:"start",default:frappe.datetime.get_today(),change:load});
 const days=page.add_field({label:__("Days"),fieldtype:"Int",fieldname:"days",default:14,change:load});
 page.add_inner_button(__("Create Tasks"),async()=>{await frappe.call({method:'hotel_pms.turnover.create_turnover_tasks',args:{property:property.get_value(),start_date:start.get_value(),days:days.get_value()},freeze:true});load();});
 page.add_inner_button(__("Refresh"),load);
 const body=$(`<div><style>.htp-table{width:100%;margin-top:14px}.htp-table th,.htp-table td{padding:7px;border-bottom:1px solid var(--border-color)}.risk-Critical{color:var(--red-600);font-weight:700}.risk-High{color:var(--orange-600);font-weight:700}</style><div class="htp-summary"></div><table class="htp-table"><thead><tr><th>${__('Date')}</th><th>${__('Room')}</th><th>${__('Departure')}</th><th>${__('Next Arrival')}</th><th>${__('Window')}</th><th>${__('Risk')}</th><th>${__('Task')}</th></tr></thead><tbody></tbody></table></div>`).appendTo(page.main);
 const e=x=>frappe.utils.escape_html(String(x??''));
 async function load(){if(!property.get_value())return;const r=await frappe.call({method:'hotel_pms.turnover.get_turnover_plan',args:{property:property.get_value(),start_date:start.get_value(),days:days.get_value()}});const d=r.message||{};body.find('tbody').html((d.rows||[]).map(x=>`<tr><td>${e(x.departure_date)}</td><td>${e(x.room_number)}</td><td>${e(x.reservation)}</td><td>${e(x.next_reservation||'-')} ${e(x.next_guest||'')}</td><td>${x.available_minutes==null?'-':e(x.available_minutes)+' min'}</td><td class="risk-${e(x.risk)}">${e(x.risk)}</td><td>${e(x.task?.name||'Not created')} · ${e(x.task?.status||'')}</td></tr>`).join('')||`<tr><td colspan="7">${__('No turnovers')}</td></tr>`);body.find('.htp-summary').html((d.cleaner_conflicts||[]).length?`<div class="alert alert-warning">${__('Cleaner assignment conflicts')}: ${(d.cleaner_conflicts||[]).map(x=>e(x.assigned_to)+' ['+e(x.rooms.join(', '))+']').join('; ')}</div>`:`<div class="alert alert-success">${__('No cleaner assignment conflicts detected.')}</div>`);}
 frappe.db.get_single_value('Hotel PMS Settings','default_property').then(v=>{if(v)property.set_value(v)});
};