frappe.pages["hotel-communications"].on_page_load=function(wrapper){
 const page=frappe.ui.make_app_page({parent:wrapper,title:__("Hotel Communications"),single_column:true});
 const property=page.add_field({label:__("Property"),fieldtype:"Link",fieldname:"property",options:"Hotel Property"});
 page.add_inner_button(__("Refresh"),load);page.add_inner_button(__("Connections"),()=>frappe.set_route("List","Hotel Channel Connection"));
 page.add_inner_button(__("Send Message"),send);
 const body=$(`<div><style>.hcom-row{padding:10px;border-bottom:1px solid var(--border-color)}.hcom-meta{color:var(--text-muted);font-size:12px}.hcom-in{border-left:4px solid #5e64ff}.hcom-out{border-left:4px solid #29cd42}.hcom-failed{background:var(--bg-red)}</style><div class="hcom-list"></div></div>`).appendTo(page.main);
 const e=v=>frappe.utils.escape_html(String(v??""));
 async function load(){const r=await frappe.call({method:"hotel_pms.communications.get_communication_console",args:{property:property.get_value(),limit:150}});body.find('.hcom-list').html((r.message.messages||[]).map(x=>`<div class="hcom-row ${x.direction==='Inbound'?'hcom-in':'hcom-out'} ${['Failed','Dead Letter'].includes(x.status)?'hcom-failed':''}"><b>${e(x.direction)} · ${e(x.status)}</b><div>${e(x.content)}</div><div class="hcom-meta">${e(x.property)} · ${e(x.reservation||'')} · ${e(x.from_number||x.to_number||'')} · ${e(x.creation)}</div>${x.direction==='Inbound'&&!x.maintenance_ticket?`<button class="btn btn-xs btn-default make-ticket" data-name="${e(x.name)}">${__("Create Maintenance Ticket")}</button>`:''}</div>`).join('')||`<div class="text-muted">${__("No messages")}</div>`);body.find('.make-ticket').on('click',async function(){const name=$(this).data('name');const r=await frappe.call({method:"hotel_pms.communications.create_maintenance_from_message",args:{message_name:name},freeze:true});frappe.set_route("Form","Hotel Maintenance Ticket",r.message.maintenance_ticket);});}
 function send(){const d=new frappe.ui.Dialog({title:__("Send WhatsApp Message"),fields:[{fieldname:"property",label:__("Property"),fieldtype:"Link",options:"Hotel Property",default:property.get_value(),reqd:1},{fieldname:"to_number",label:__("Phone"),fieldtype:"Data",reqd:1},{fieldname:"reservation",label:__("Reservation"),fieldtype:"Link",options:"Hotel Reservation"},{fieldname:"content",label:__("Message"),fieldtype:"Small Text",reqd:1}],primary_action_label:__("Send"),primary_action:async v=>{await frappe.call({method:"hotel_pms.communications.send_staff_text",args:{...v,request_key:crypto.randomUUID()},freeze:true});d.hide();load();}});d.show();}
 load();
};
