frappe.pages["hotel-production-gate"].on_page_load=function(wrapper){
 const page=frappe.ui.make_app_page({parent:wrapper,title:__("Hotel Production Gate"),single_column:true});
 const run=page.add_field({label:__("Gate Run"),fieldtype:"Link",fieldname:"run",options:"Hotel Production Gate Run",change:load});
 const body=$(`<div><style>.pg-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.pg-card{border:1px solid var(--border-color);padding:12px;border-radius:8px}.pg-table{width:100%;margin-top:14px}.pg-table th,.pg-table td{border-bottom:1px solid var(--border-color);padding:7px;text-align:left}.pg-bad{color:var(--red-500)}.pg-good{color:var(--green-500)}</style><div class="pg-grid"></div><div class="pg-content"></div></div>`).appendTo(page.main);
 const e=x=>frappe.utils.escape_html(String(x??""));
 const canManage=frappe.user_roles.includes("System Manager")||frappe.user_roles.includes("Hotel Manager");
 if(canManage) page.add_inner_button(__("Create Gate Run"),async()=>{const p=await new Promise(resolve=>frappe.prompt([{fieldname:"property",label:__("Property"),fieldtype:"Link",options:"Hotel Property"},{fieldname:"environment_name",label:__("Environment"),fieldtype:"Select",options:"Staging\nPre-production\nProduction",default:"Staging",reqd:1},{fieldname:"expected_frappe_version",label:__("Expected Frappe Version"),fieldtype:"Data",reqd:1},{fieldname:"expected_erpnext_version",label:__("Expected ERPNext Version"),fieldtype:"Data",reqd:1},{fieldname:"expected_image_digest",label:__("Expected Image Digest"),fieldtype:"Data",reqd:1}],v=>resolve(v),__("Create Production Gate")));if(!p)return;const r=await frappe.call({method:"hotel_pms.production_gate.create_gate_run",args:p,freeze:true});run.set_value(r.message.name);});
 if(canManage) page.add_inner_button(__("Run Automated Checks"),async()=>{if(!run.get_value())return frappe.msgprint(__("Select a gate run."));await frappe.call({method:"hotel_pms.production_gate.execute_automated_checks",args:{run_name:run.get_value()},freeze:true});load();});
 if(canManage) page.add_inner_button(__("Record Manual Evidence"),async()=>{if(!run.get_value())return frappe.msgprint(__("Select a gate run."));frappe.prompt([{fieldname:"check_code",label:__("Check Code"),fieldtype:"Data",reqd:1},{fieldname:"status",label:__("Status"),fieldtype:"Select",options:"Passed\nWarning\nFailed\nNot Applicable",reqd:1},{fieldname:"measured_value",label:__("Measured Value"),fieldtype:"Data"},{fieldname:"evidence_url",label:__("Evidence URL"),fieldtype:"Data"},{fieldname:"details",label:__("Details"),fieldtype:"Long Text"}],async v=>{await frappe.call({method:"hotel_pms.production_gate.record_manual_check",args:{run_name:run.get_value(),...v},freeze:true});load();},__("Manual Gate Evidence"));});
 page.add_inner_button(__("Department Sign-off"),async()=>{if(!run.get_value())return frappe.msgprint(__("Select a gate run."));frappe.prompt([{fieldname:"department",label:__("Department"),fieldtype:"Select",options:"Front Office\nHousekeeping\nEngineering\nSales & Banquet\nF&B\nFinance\nIT\nManagement",reqd:1},{fieldname:"status",label:__("Status"),fieldtype:"Select",options:"Approved\nRejected",reqd:1},{fieldname:"comments",label:__("Comments"),fieldtype:"Small Text"}],async v=>{await frappe.call({method:"hotel_pms.production_gate.submit_signoff",args:{run_name:run.get_value(),...v},freeze:true});load();},__("Department Sign-off"));});
 if(frappe.user_roles.includes("System Manager")) page.add_inner_button(__("Final Decision"),async()=>{if(!run.get_value())return frappe.msgprint(__("Select a gate run."));frappe.prompt([{fieldname:"decision",label:__("Decision"),fieldtype:"Select",options:"Go\nNo-Go\nRollback",reqd:1},{fieldname:"notes",label:__("Decision Notes"),fieldtype:"Long Text",reqd:1}],async v=>{await frappe.call({method:"hotel_pms.production_gate.decide_go_live",args:{run_name:run.get_value(),...v},freeze:true});load();},__("Final Go-live Decision"));});
 async function load(){const r=await frappe.call({method:"hotel_pms.production_gate.get_gate_dashboard",args:{run_name:run.get_value()||null}});const d=r.message;if(!run.get_value()){body.find('.pg-grid').empty();body.find('.pg-content').html(`<h4>${__("Recent Runs")}</h4><table class="pg-table"><tr><th>Run</th><th>Property</th><th>Release</th><th>Status</th><th>Decision</th></tr>${(d.runs||[]).map(x=>`<tr><td><a href="#" data-run="${e(x.name)}">${e(x.name)}</a></td><td>${e(x.property||'All')}</td><td>${e(x.release_version)}</td><td>${e(x.status)}</td><td>${e(x.go_live_decision)}</td></tr>`).join('')}</table>`);body.find('[data-run]').on('click',function(ev){ev.preventDefault();run.set_value($(this).data('run'));});return;}
 body.find('.pg-grid').html(`<div class="pg-card"><small>Status</small><h3>${e(d.status)}</h3></div><div class="pg-card"><small>Blockers</small><h3 class="pg-bad">${e(d.blocker_count)}</h3></div><div class="pg-card"><small>Warnings</small><h3>${e(d.warning_count)}</h3></div><div class="pg-card"><small>Decision</small><h3>${e(d.go_live_decision)}</h3></div>`);
 body.find('.pg-content').html(`<h4>${__("Checks")}</h4><table class="pg-table"><tr><th>Category</th><th>Check</th><th>Status</th><th>Measured</th><th>Threshold</th><th>Details</th></tr>${(d.checks||[]).map(x=>`<tr><td>${e(x.category)}</td><td>${e(x.title)}</td><td class="${x.status==='Failed'?'pg-bad':x.status==='Passed'?'pg-good':''}">${e(x.status)}</td><td>${e(x.measured_value)}</td><td>${e(x.threshold)}</td><td>${e(x.details)}</td></tr>`).join('')}</table><h4>${__("Sign-offs")}</h4><table class="pg-table"><tr><th>Department</th><th>Status</th><th>Approver</th><th>Signed</th></tr>${(d.signoffs||[]).map(x=>`<tr><td>${e(x.department)}</td><td>${e(x.status)}</td><td>${e(x.approver)}</td><td>${e(x.signed_at)}</td></tr>`).join('')}</table>`);
 }
 load();
};
